servers=[
{
  :hostname => "server1",
  :ip => "127.0.0.1",
  :port => "2200",
  :box => "hashicorp/precise64",
  :ram => 512,
  :cpu => 1,
  :provisions => [".bootstrap/bootstrap.sh","fixScripts/exercise1-fix.sh","fixScripts/exercise2-fix.sh","fixScripts/exercise3-fix.sh","fixScripts/exercise5-fix_server1.sh","fixScripts/exercise4-fix_server1.sh"]
},
{
  :hostname => "server2",
  :ip => "127.0.0.1",
  :port => "2201",
  :box => "hashicorp/precise64",
  :ram => 512,
  :cpu => 1,
  :provisions => ["fixScripts/exercise5-fix_server2.sh","fixScripts/exercise4-fix_server2.sh"]
}
]

Vagrant.configure(2) do |config|
  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
        machine [:provisions].each do |script|
           node.vm.provision :shell, :path => script
        end
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]
      node.vm.provider "virtualbox" do |vb|
        node.vm.base_mac = "080027880CA6"
        vb.memory = machine[:ram]
        vb.cpus = machine[:cpu]
      end
    end
  end
end


